ALTER TABLE HR.EMPLOYEES
ADD MAX_SALARY NUMBER;

UPDATE HR.EMPLOYEES
SET MAX_SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES);

DELETE FROM HR.EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM HR.EMPLOYEES);

SELECT * FROM HR.EMPLOYEES;

CREATE INDEX DPR_NAME_IDX
ON HR.DEPARTMENTS (DEPARTMENT_NAME);

ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT CNSTR_SALARY 
CHECK (SALARY BETWEEN 1000 AND 100000);

DROP INDEX DPR_NAME_IDX;

ALTER TABLE HR.EMPLOYEES
DISABLE CONSTRAINT CNSTR_SALARY;

ALTER TABLE HR.EMPLOYEES
ENABLE CONSTRAINT CNSTR_SALARY;

CREATE TABLE EMP_DEPT AS
SELECT DISTINCT DEPARTMENT_ID
FROM HR.EMPLOYEES;

ALTER TABLE EMP_DEPT
ADD DEPARTMENT_NAME VARCHAR2(50);


MERGE INTO EMP_DEPT target
USING (
    SELECT DEPARTMENT_ID, DEPARTMENT_NAME
    FROM HR.DEPARTMENTS
) source
ON (target.DEPARTMENT_ID = source.DEPARTMENT_ID)
WHEN MATCHED THEN
    UPDATE SET target.DEPARTMENT_NAME = source.DEPARTMENT_NAME
WHEN NOT MATCHED THEN
    INSERT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (source.DEPARTMENT_ID, source.DEPARTMENT_NAME);
    
    
WITH Employee_Info AS (
    SELECT 
        FIRST_NAME, 
        LAST_NAME, 
        JOB_ID, 
        DEPARTMENT_ID
    FROM HR.EMPLOYEES WHERE JOB_ID LIKE 'S%'
), 
Job_Info AS (
    SELECT 
        JOB_ID, 
        JOB_TITLE, 
        MIN_SALARY, 
        MAX_SALARY
    FROM HR.JOBS
),
Full_Employee_Info AS (
    SELECT 
        E.FIRST_NAME, 
        E.LAST_NAME, 
        E.JOB_ID, 
        E.DEPARTMENT_ID, 
        J.JOB_TITLE, 
        J.MIN_SALARY, 
        J.MAX_SALARY, 
        D.DEPARTMENT_NAME
    FROM Employee_Info E
    JOIN Job_Info J ON E.JOB_ID = J.JOB_ID
    JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
)
SELECT 
    FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME, 
    JOB_ID, 
    JOB_TITLE, 
    MIN_SALARY, 
    MAX_SALARY, 
    DEPARTMENT_NAME
FROM Full_Employee_Info ORDER BY FULL_NAME;


