SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME
    FROM EMPLOYEES, DEPARTMENTS WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
    
SELECT EMPLOYEE_ID, MANAGER_ID
    FROM EMPLOYEES;

SELECT 
    SUBSTR(PHONE_NUMBER, 1, 3) AS operator,
    COUNT(*) AS total_subscribers
FROM 
    HR.EMPLOYEES GROUP BY SUBSTR(PHONE_NUMBER, 1, 3) ORDER BY operator;
    
    
CREATE TABLE HR.EMP AS
SELECT * FROM HR.EMPLOYEES WHERE 1=0;

INSERT INTO HR.EMP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (5, 'John', 'Doe', 'JDOE', '1234567890', SYSDATE, 'IT_PROG', 6000, NULL, 100, 60);

SELECT * FROM HR.EMP;

UPDATE HR.EMP
SET PHONE_NUMBER = '0987654321', SALARY = 7000 WHERE EMPLOYEE_ID = 5;

DELETE FROM HR.EMP WHERE EMPLOYEE_ID = 5;

DROP TABLE HR.EMP;


SELECT 
    SUBSTR(FIRST_NAME, 1, 2) || LPAD('*', LENGTH(FIRST_NAME) - 2, '*') AS MASKED_FIRST_NAME,
    SUBSTR(LAST_NAME, 1, 2) || LPAD('*', LENGTH(LAST_NAME) - 2, '*') AS MASKED_LAST_NAME
FROM 
    HR.EMPLOYEES;
